# Generated by Django 3.1.2 on 2021-04-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='query',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
