# Generated by Django 3.1.2 on 2021-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_message_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyform',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
