# Generated by Django 3.1.2 on 2021-04-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('power', '0004_auto_20210407_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL),
        ),
    ]
