# Generated by Django 3.1.2 on 2021-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0007_auto_20210407_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyform',
            name='response',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
